{"name": "Попытка изменения почты авторизованного пользователя на уже существующую почту", "status": "failed", "statusDetails": {"message": "AssertionError: assert (200 == 403)\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user.TestUpdateUser object at 0x000001DE904A9C40>\ncreate_and_delete_user = (<Response [200]>, {'email': 'bdcwirlbme@yandex.ru', 'name': 'tfhjhggenx', 'password': 'dgtkxgyutr'}, {'email': 'bdcwi...mM4OWVkMjgwMDAxYjM5Y2UxZCIsImlhdCI6MTcwMzYxMzEyOCwiZXhwIjoxNzAzNjE0MzI4fQ.3djKBQr9gSyGIVIoNVK5St7fhBjk8xVQc-7h_mBDq8A')\n\n    @allure.title('Попытка изменения почты авторизованного пользователя на уже существующую почту')\n    def test_update_user_email_of_signed_in_user(self, create_and_delete_user):\n        new_email = {\"email\": create_and_delete_user[2]['email']}\n        token = {'Authorization': create_and_delete_user[3]}\n        response = requests.patch(Links.user_url, headers=token, data=new_email)\n>       assert response.status_code == 403 and response.json()['message'] == \"User with such email already exists\"\nE       assert (200 == 403)\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_user.py:62: AssertionError"}, "start": 1703613128605, "stop": 1703613129021, "uuid": "1f29fdaa-d713-4d01-8ee8-bf9b0ad63d0e", "historyId": "f254c435c6a05b2a4e8b055f44ea9e80", "testCaseId": "f254c435c6a05b2a4e8b055f44ea9e80", "fullName": "tests.test_user.TestUpdateUser#test_update_user_email_of_signed_in_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user"}, {"name": "subSuite", "value": "TestUpdateUser"}, {"name": "host", "value": "Ya"}, {"name": "thread", "value": "27344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user"}]}